"""ParaBank REST API tests — customer registration (POST /register.htm).

Defects discovered by exploratory/monkey testing:
  D-16  A street/state value beyond ~40 characters fails registration but reports
        the wrong error ("This username already exists") instead of a field-length
        validation message — misleading even though the username is guaranteed fresh.
  D-17  phoneNumber is not enforced as a required field, unlike state/zipCode/ssn.
"""

import allure
import pytest

from utils.parabank_api import REGISTRATION_SUCCESS_MARKER, submit_registration

pytestmark = [
    allure.feature("Registration"),
    allure.story("Customer registration API"),
    allure.severity(allure.severity_level.NORMAL),
]


@pytest.mark.smoke
@pytest.mark.api
def test_registration_with_valid_fields_succeeds(base_url: str) -> None:
    response = submit_registration(base_url)
    with allure.step("Verify the success marker is present"):
        assert REGISTRATION_SUCCESS_MARKER in response.text


@pytest.mark.api
def test_registration_missing_state_is_rejected(base_url: str) -> None:
    response = submit_registration(base_url, state="")
    with allure.step("Verify a validation error, not success"):
        assert REGISTRATION_SUCCESS_MARKER not in response.text
        assert "State is required" in response.text


@pytest.mark.api
def test_registration_missing_zip_is_rejected(base_url: str) -> None:
    response = submit_registration(base_url, zipCode="")
    with allure.step("Verify a validation error, not success"):
        assert REGISTRATION_SUCCESS_MARKER not in response.text
        assert "Zip Code is required" in response.text


@pytest.mark.api
@pytest.mark.xfail(
    strict=True,
    reason="Known defect D-17: phoneNumber is not enforced as required, unlike state/zipCode/ssn",
)
def test_registration_missing_phone_is_rejected(base_url: str) -> None:
    response = submit_registration(base_url, phoneNumber="")
    with allure.step("Verify a validation error for a missing phone number"):
        assert REGISTRATION_SUCCESS_MARKER not in response.text


@pytest.mark.api
@pytest.mark.xfail(
    strict=True,
    reason="Known defect D-16: an overlong street address fails registration with a "
    "misleading 'username already exists' error instead of a field-length message",
)
def test_registration_with_overlong_street_reports_correct_error(base_url: str) -> None:
    # The username is freshly generated by submit_registration on every call, so it
    # cannot legitimately already exist — a false collision report is the defect.
    response = submit_registration(base_url, street="A" * 60)
    with allure.step("A fresh username must not be reported as already existing"):
        assert "already exists" not in response.text
